[server]
JwtSecret=''
JwtIssue='wxcomponent'
JwtExpireTime=43200
AesKey=''

[wxapi]
UseCloudBaseAccessToken=false
UseComponentAccessToken=true # 腾讯云部署不需要去获取token，设置false
UseHttps=true # 腾讯云部署不需要去获取token，设置false

[comm]
Version='2.1.0'

[wxcallback]
# 微信开放平台「消息校验Token」（自建服务器时必填，云托管可留空）
Token='yysh'
# 微信开放平台「消息加解密Key」43位，自建服务器时必填，云托管可留空
EncodingAESKey='yyshyyshyyshyyshyyshyyshyyshyyshyyshyyshyys'