[server]
JwtSecret=''
JwtIssue='wxcomponent'
JwtExpireTime=43200
AesKey=''

[wxapi]
UseCloudBaseAccessToken=false
UseComponentAccessToken=true # 腾讯云部署不需要去获取token，设置false
UseHttps=true # 腾讯云部署不需要去获取token，设置false

[comm]
Version='2.1.0'